name: Update Check
on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * 2,3,4"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 18
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew runScript
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Update readme
            commit_author: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
